# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m2pUBbgJjKEdHs5LDayGWwm1qU-3P8lj
"""

!pip install albumentations --quiet

import zipfile
import os

zip_path = "/content/Table detection.v1i.yolov8.zip"
extract_dir = "/content/table_dataset"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_dir)

image_dir = os.path.join(extract_dir, "train", "images")
label_dir = os.path.join(extract_dir, "train", "labels")

output_img_dir = "/content/synthetic_dataset/images"
output_lbl_dir = "/content/synthetic_dataset/labels"
os.makedirs(output_img_dir, exist_ok=True)
os.makedirs(output_lbl_dir, exist_ok=True)

import albumentations as A
from albumentations.pytorch import ToTensorV2

transform = A.Compose([
    A.HorizontalFlip(p=0.5),
    A.RandomBrightnessContrast(p=0.5),
    A.Rotate(limit=15, p=0.5),
    A.Blur(p=0.3),
    A.RandomScale(scale_limit=0.2, p=0.3)
], bbox_params=A.BboxParams(format='yolo', label_fields=['class_labels']))

import cv2
import glob
import random
from tqdm import tqdm

image_paths = glob.glob(os.path.join(image_dir, "*.jpg"))
target_samples = 1000
counter = 0
id_counter = 1

print(f"📈 Generating {target_samples} synthetic samples...")

while counter < target_samples:
    img_path = random.choice(image_paths)
    img_filename = os.path.basename(img_path)
    label_path = os.path.join(label_dir, img_filename.replace('.jpg', '.txt'))

    image = cv2.imread(img_path)
    if image is None:
        continue
    height, width, _ = image.shape

    bboxes = []
    class_labels = []
    if os.path.exists(label_path):
        with open(label_path, "r") as f:
            for line in f:
                parts = line.strip().split()
                if len(parts) == 5:
                    cls, x, y, w, h = map(float, parts)
                    bboxes.append([x, y, w, h])
                    class_labels.append(int(cls))

    try:
        transformed = transform(image=image, bboxes=bboxes, class_labels=class_labels)
        transformed_image = transformed['image']
        transformed_bboxes = transformed['bboxes']
        transformed_labels = transformed['class_labels']

        new_img_name = f"synthetic_{id_counter}.jpg"
        new_lbl_name = f"synthetic_{id_counter}.txt"

        cv2.imwrite(os.path.join(output_img_dir, new_img_name), transformed_image)

        with open(os.path.join(output_lbl_dir, new_lbl_name), 'w') as f:
            for bbox, cls in zip(transformed_bboxes, transformed_labels):
                x, y, w, h = bbox
                f.write(f"{cls} {x:.6f} {y:.6f} {w:.6f} {h:.6f}\n")

        counter += 1
        id_counter += 1

    except Exception as e:
        print("❌ Skipped one due to error:", e)
        continue

print(f"\n✅ Finished! Total synthetic images: {counter}")

import shutil

shutil.make_archive("/content/synthetic_table_dataset", 'zip', "/content/synthetic_dataset")

from google.colab import files
files.download("/content/synthetic_table_dataset.zip")

import shutil
import os

combined_img_dir = "/content/combined_dataset/images"
combined_lbl_dir = "/content/combined_dataset/labels"
os.makedirs(combined_img_dir, exist_ok=True)
os.makedirs(combined_lbl_dir, exist_ok=True)

# Copy original
for src_dir in [image_dir, output_img_dir]:
    for img_file in os.listdir(src_dir):
        shutil.copy(os.path.join(src_dir, img_file), combined_img_dir)

for src_dir in [label_dir, output_lbl_dir]:
    for lbl_file in os.listdir(src_dir):
        shutil.copy(os.path.join(src_dir, lbl_file), combined_lbl_dir)

print("✅ Combined original and synthetic data!")

from sklearn.model_selection import train_test_split
import os

all_images = os.listdir(combined_img_dir)
train_imgs, val_imgs = train_test_split(all_images, test_size=0.2, random_state=42)

# Create YOLOv8 folder structure
for split in ['train', 'val']:
    os.makedirs(f"/content/final_dataset/images/{split}", exist_ok=True)
    os.makedirs(f"/content/final_dataset/labels/{split}", exist_ok=True)

# Move files
for img in train_imgs:
    shutil.copy(os.path.join(combined_img_dir, img), f"/content/final_dataset/images/train/{img}")
    lbl = img.replace(".jpg", ".txt")
    shutil.copy(os.path.join(combined_lbl_dir, lbl), f"/content/final_dataset/labels/train/{lbl}")

for img in val_imgs:
    shutil.copy(os.path.join(combined_img_dir, img), f"/content/final_dataset/images/val/{img}")
    lbl = img.replace(".jpg", ".txt")
    shutil.copy(os.path.join(combined_lbl_dir, lbl), f"/content/final_dataset/labels/val/{lbl}")

!pip install ultralytics --upgrade --quiet

data_yaml = """
path: /content/final_dataset
train: images/train
val: images/val
names: ['table']
"""

with open('/content/final_dataset/data.yaml', 'w') as f:
    f.write(data_yaml)

from ultralytics import YOLO

model = YOLO('yolov8n.pt')  # or yolov8s.pt for better accuracy
model.train(data='/content/final_dataset/data.yaml', epochs=6, imgsz=640, batch=16)

from ultralytics import YOLO
from google.colab import files
from IPython.display import display, Markdown
import cv2
import matplotlib.pyplot as plt
# Load trained model
model = YOLO("/content/runs/detect/train2/weights/best.pt")  # your trained YOLOv8 model path

# Predict on test image

results = model.predict("/content/synthetic_dataset/images/synthetic_999.jpg", conf=0.5)

# Access detections
boxes = results[0].boxes

if len(boxes) > 0:
    display(Markdown("**✅ Table is Present!**"))
    for i, box in enumerate(boxes):
        cls_id = int(box.cls[0])  # class ID
        conf = float(box.conf[0])  # confidence score
        display(Markdown(f"**-  Confidence: {conf:.2f}**"))
else:
    display(Markdown("**❌ Table is not Present.**"))


display(Markdown(f"**- Number of detections: {len(boxes)}**"))

results[0].show()

