# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HUsq72nTNC6ICghaH4ddW6-NE8nScaEX
"""

from google.colab import files
uploaded = files.upload()  # Upload the Roboflow YOLOv8 zip here

import zipfile
import os

zip_path = list(uploaded.keys())[0]  # gets uploaded filename
extract_path = "/content/tool_dataset"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("✅ Extracted to:", extract_path)

!pip install ultralytics --upgrade

from ultralytics import YOLO

model = YOLO('/content/yolov8n.pt')  # you can use yolov8m.pt or yolov8s.pt for better accuracy

model.train(
    data='/content/tool_dataset/data.yaml',
    epochs=6,
    imgsz=640,
    batch=16
)

# Load the best trained model
model = YOLO('/content/runs/detect/train/weights/best.pt')

# Upload and test an image
from google.colab import files
uploaded = files.upload()

import cv2
from IPython.display import Image, display

image_path = list(uploaded.keys())[0]
results = model(image_path, save=True)

# Show output image
from glob import glob
from IPython.display import Image
Image(filename=glob("runs/detect/predict/*.jpg")[0])