# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zzoGbUNsQMom5mBox23wGe4383GC-D9y
"""

import pandas as pd
import numpy as np
from datetime import datetime
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, ConfusionMatrixDisplay
from imblearn.combine import SMOTETomek
import matplotlib.pyplot as plt
import seaborn as snsg
import shap
from google.colab import files

uploaded = files.upload()

filename = next(iter(uploaded))
df = pd.read_csv(filename)
print(type(df))
print(df.head())

if df['Avg Load'].dtype == 'object':
    df['Avg Load'] = df['Avg Load'].str.replace('%', '', regex=False).astype(float)
df['Usage Since Last Replace'] = (
    df['Usage Since Last Replace'].astype(str).str.replace(' hours', '', regex=False).astype(float)
)

df['Last Replaced'] = pd.to_datetime(df['Last Replaced'])

X = df.drop(columns=['Predicted Demand'])
y = df['Predicted Demand']
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

X_train_raw, X_test_raw, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)

numeric_features = ['Usage Since Last Replace', 'Failure Count', 'Avg Load']
categorical_features = ['Component', 'Environment', 'Location']
numeric_pipeline = Pipeline([
    ('scaler', StandardScaler())
])
categorical_pipeline = Pipeline([
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])
preprocessor = ColumnTransformer([
    ('num', numeric_pipeline, numeric_features),
    ('cat', categorical_pipeline, categorical_features)
])
X_train_encoded = preprocessor.fit_transform(X_train_raw)
X_test_encoded = preprocessor.transform(X_test_raw)

smt = SMOTETomek(random_state=42)
X_train_balanced, y_train_balanced = smt.fit_resample(X_train_encoded, y_train)

model = RandomForestClassifier(random_state=42)
model.fit(X_train_balanced, y_train_balanced)

y_pred = model.predict(X_test_encoded)
print("\n✅ Accuracy:", accuracy_score(y_test, y_pred))
print("\n📊 Classification Report:")
print(classification_report(y_test, y_pred, target_names=label_encoder.classes_))
ConfusionMatrixDisplay.from_estimator(model, X_test_encoded, y_test, display_labels=label_encoder.classes_, cmap='Blues')
plt.title("Confusion Matrix")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
demand_order = ['Low', 'Medium', 'High']
plt.figure(figsize=(10, 5))
sns.stripplot(data=df, x='Failure Count', y='Predicted Demand', order=demand_order, jitter=0.2, palette='Set1', alpha=0.7)
plt.title(" Dot Plot: Failure Count vs Predicted Demand")
plt.xlabel("Failure Count")
plt.ylabel("Predicted Demand")
plt.grid(True, axis='x', linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
def explain_prediction_contribution(sample_dict):
    component_score = 2 if sample_dict['Component'] in ['Pump', 'Valve'] else 0
    environment_score = 2 if sample_dict['Environment'] == 'Hot' else 0
    location_score = 1 if sample_dict['Location'] == 'Plant-3' else 0
    failure_score = 3 if sample_dict['Failure Count'] >= 4 else (2 if sample_dict['Failure Count'] == 3 else 0)
    usage_score = 2 if sample_dict['Usage Since Last Replace'] >= 800 else (-1 if sample_dict['Usage Since Last Replace'] <= 200 else 1)
    load_score = 1 if sample_dict['Avg Load'] >= 85 else (-1 if sample_dict['Avg Load'] <= 60 else 0)
    contributions = {
        f"Component ({sample_dict['Component']})": component_score,
        f"Environment ({sample_dict['Environment']})": environment_score,
        f"Failure Count ({sample_dict['Failure Count']})": failure_score,
        f"Usage Since Last Replace ({sample_dict['Usage Since Last Replace']})": usage_score,
        f"Avg Load ({sample_dict['Avg Load']}%)": load_score,
        f"Location ({sample_dict['Location']})": location_score
    }
    total_score = sum(contributions.values())
    if total_score >= 7:
        predicted_label = "High"
    elif total_score <= 2:
        predicted_label = "Low"
    else:
        predicted_label = "Medium"

    # Plot bar chart
    plt.figure(figsize=(10, 6))
    bars = plt.barh(list(contributions.keys()), list(contributions.values()), color='skyblue')
    plt.axvline(0, color='black', linewidth=0.5)
    plt.title(f" Feature Contributions to Predicted Demand Score ({predicted_label})")
    plt.xlabel("Score Impact")
    plt.grid(axis='x', linestyle='--', alpha=0.5)
    for bar in bars:
        width = bar.get_width()
        plt.text(width + 0.1 if width >= 0 else width - 0.6,
                 bar.get_y() + bar.get_height() / 2,
                 f"{width:+}", va='center')
    plt.tight_layout()
    plt.show()

# @title  Component Demand
import matplotlib.pyplot as plt
component = "Pump" # @param ["Pump", "Valve", "Sensor", "Filter", "Bearing"]
environment = "Cold" # @param ["Hot", "Cold", "Mixed"]
location = "Plant-1" # @param ["Plant-1", "Plant-2", "Plant-3"]
failure_count = 0 # @param {type:"slider", min:0, max:10, step:1}
usage = 0 # @param {"type":"slider","min":0,"max":1000,"step":50}
avg_load = 95 # @param {"type":"slider","min":0,"max":100,"step":5}
component_score = 2 if component in ['Pump', 'Valve'] else 0
environment_score = 2 if environment == 'Hot' else 0
location_score = 1 if location == 'Plant-3' else 0
failure_score = 3 if failure_count >= 4 else (2 if failure_count == 3 else 0)
usage_score = 2 if usage >= 800 else (-1 if usage <= 200 else 1)
load_score = 1 if avg_load >= 85 else (-1 if avg_load <= 60 else 0)

score = component_score + environment_score + location_score + failure_score + usage_score + load_score
if score >= 7:
    label = "High"
elif score <= 2:
    label = "Low"
else:
    label = "Medium"
print(f"🔢 Score: {score}")
print(f"🔮 Predicted Demand: {label}")
contributions = {
    f"Component ({component})": component_score,
    f"Environment ({environment})": environment_score,
    f"Failure Count ({failure_count})": failure_score,
    f"Usage Since Last Replace ({usage})": usage_score,
    f"Avg Load ({avg_load}%)": load_score,
    f"Location ({location})": location_score
}
plt.figure(figsize=(10, 6))
bars = plt.barh(list(contributions.keys()), list(contributions.values()), color='skyblue')
plt.axvline(0, color='black', linewidth=0.8)
plt.title(f"Feature Contributions to Predicted Demand Score ({label})")
plt.xlabel("Score Impact")
for bar in bars:
    width = bar.get_width()
    plt.text(width + 0.1 if width > 0 else width - 0.6,
             bar.get_y() + bar.get_height() / 2,
             f"{width:+}", va='center')
plt.tight_layout()
plt.show()

explainer = shap.Explainer(model.predict_proba, X_train_balanced)

sample_index = 0
sample_input = X_test_encoded[sample_index].reshape(1, -1)
pred_class_index = model.predict(sample_input)[0]
pred_class_label = label_encoder.inverse_transform([pred_class_index])[0]

shap_values = explainer(sample_input)

shap_vals_array = shap_values.values[0][pred_class_index]
base_val = shap_values.base_values[0][pred_class_index]
feature_names = shap_values.feature_names
input_data = shap_values.data[0]

shap_expl = shap.Explanation(
    values=shap_vals_array,
    base_values=base_val,
    data=input_data,
    feature_names=feature_names
)

print(f"🔮 Predicted Demand: {label}")
shap.plots.waterfall(shap_expl)

import joblib

# After training
joblib.dump(model, "model.pkl")
joblib.dump(preprocessor, "preprocessor.pkl")
joblib.dump(label_encoder, "label_encoder.pkl")

import os
print(os.listdir())

import gradio as gr
import pandas as pd
import matplotlib.pyplot as plt
import io, base64
from joblib import load

# Load model and preprocessor
model = load("model.pkl")
preprocessor = load("preprocessor.pkl")
label_encoder = load("label_encoder.pkl")

# Prediction function
def predict(component, environment, location, failure_count, usage, avg_load):
    df = pd.DataFrame([{
        "Component": component,
        "Environment": environment,
        "Location": location,
        "Failure Count": failure_count,
        "Usage Since Last Replace": usage,
        "Avg Load": avg_load
    }])

    try:
        X = preprocessor.transform(df)
        pred_encoded = model.predict(X)[0]
        pred_label = label_encoder.inverse_transform([pred_encoded])[0]

        # Simple bar explanation
        scores = {
            f"Component ({component})": 2 if component in ['Pump', 'Valve'] else 0,
            f"Environment ({environment})": 2 if environment == 'Hot' else 0,
            f"Location ({location})": 1 if location == 'Plant-3' else 0,
            f"Failure Count ({failure_count})": 3 if failure_count >= 4 else (2 if failure_count == 3 else 0),
            f"Usage Since Last Replace ({usage})": 2 if usage >= 800 else (-1 if usage <= 200 else 1),
            f"Avg Load ({avg_load}%)": 1 if avg_load >= 85 else (-1 if avg_load <= 60 else 0)
        }

        fig, ax = plt.subplots(figsize=(8, 5))
        bars = ax.barh(list(scores.keys()), list(scores.values()), color='skyblue')
        ax.axvline(0, color='black')
        ax.set_title(f"Feature Contributions ({pred_label})")
        ax.set_xlabel("Score")
        for bar in bars:
            ax.text(bar.get_width(), bar.get_y() + bar.get_height()/2, f"{bar.get_width():+}", va='center')

        buf = io.BytesIO()
        plt.tight_layout()
        plt.savefig(buf, format='png')
        plt.close()
        img_data = base64.b64encode(buf.getvalue()).decode()
        html_img = f'<img src="data:image/png;base64,{img_data}"/>'

        return pred_label, html_img

    except Exception as e:
        return "Error", f"<pre>{e}</pre>"

# Gradio app
gr.Interface(
    fn=predict,
    inputs=[
        gr.Dropdown(["Pump", "Valve", "Sensor", "Filter", "Bearing"], label="Component"),
        gr.Dropdown(["Hot", "Cold", "Mixed"], label="Environment"),
        gr.Dropdown(["Plant-1", "Plant-2", "Plant-3"], label="Location"),
        gr.Slider(0, 10, step=1, label="Failure Count"),
        gr.Slider(0, 1000, step=50, label="Usage Since Last Replace"),
        gr.Slider(40, 100, step=5, label="Avg Load (%)")
    ],
    outputs=[
        gr.Textbox(label="Predicted Demand"),
        gr.HTML(label="Explanation")
    ],
    title="Component Demand Predictor",
    description="Enter equipment conditions to predict demand level"
).launch(debug=True)